name: Add paper to collection
description: Track a research paper to read
title: "[Title]"
assignees: []
body:
  - type: input
    id: authors
    attributes:
      label: Author(s)
      description: List all authors
      placeholder: e.g., A. Smith; B. Lee
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link
      description: URL to the paper (arXiv, publisher, etc.)
      placeholder: https://...
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: Paste the abstract or a short summary
      placeholder: >
        Brief abstract or summary…
      render: markdown
    validations:
      required: false

  - type: input
    id: doi
    attributes:
      label: DOI
      description: Digital Object Identifier (if available)
      placeholder: 10.xxxx/xxxxx
    validations:
      required: false
