name: Sync Labels from Issue to PR

on:
  pull_request:
    types: [opened]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync Labels
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prBody = context.payload.pull_request.body;
          const issueMatch = prBody ? prBody.match(/#(\d+)/) : null;
          
          if (issueMatch) {
            const issue_number = issueMatch[1];
            const issue = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            });
            const labels = issue.data.labels.map(label => label.name);
            
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });
          } else {
            console.log('No associated issue number found in the PR description.');
          }
